### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by lppt** [handcoded/fpml-toolkit-csharp#1]
Hi, looks like some files are missing. Could you please check them in?

\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Identification\UPIFormatter.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Identification\UPIExtractor.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Identification\UPISwapEmbeddedOptionExtractor.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Infoset\ProductInfoset.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\IdentifierRule.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\IExtractor.cs 
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\IFormatter.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\ISource.cs 
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\Property.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\RuleBook.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\Xml\RuleBookLoader.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\Xml\StringExtractor.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Identification\Xml\XmlSource.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\AbstractCategory.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\ApplicableDelegate.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Category.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\ClassificationScheme.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\DelegatedCategory.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\DelegatedRefinableCategory.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\RefinableCategory.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\ClassificationSchemeLoader.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\ExprNode.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\IfNode.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\RangeNode.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\ReleaseNode.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\XmlCategory.cs
\handcoded\fpml-toolkit-csharp\HandCoded\Classification\Xml\XPathNode.cs
\handcoded\fpml-toolkit-csharp\HandCoded\DataEncoding\Base32.cs 
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Classification\FpMLTaxonomy.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Classification\ISDATaxonomy.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Identification\AlternateUPI.cs
\handcoded\fpml-toolkit-csharp\HandCoded\FpML\Identification\UPI.cs

**Comment by andrew-jacobs** [comment]
I've merged in the missing files. Try resyncing.

**Comment by lppt** [comment]
Thanks a lot!
